baseurl      = "https://bouali.io/"
title        = "Tarek Bouali"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
relativeURLs = true
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = false
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
disableReadOtherPosts = false
disqusShortname = "tarek-bouali"
[permalinks]
posts = "/posts/:year/:title/"
# Social icons
[[params.social]]
name = "twitter"
url  = "https://twitter.com/iambouali"
[[params.social]]
name = "email"
url  = "mailto:me@bouali.io"
[[params.social]]
name = "github"
url  = "https://github.com/iambouali"
[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/iambouali"
[[params.social]]
name = "hackerone"
url  = "https://hackerone.com/iambouali"
[params]
customCSS = ["/scss/_custom.css"]
description = "A place where Tarek Bouali share stuff"
enableSharingButtons = true
images = [""]
defaultTheme = "light"
footerLeft = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
footerRight = "by <a href=\"https://github.com/iambouali\">iambouali</a>"
[taxonomies]
category = "blog"
tag      = "tags"
[languages]
[languages.en]
title = "Tarek Bouali"
keywords = ""
readOtherPosts = "Read other posts"
[languages.en.params.logo]
logoText     = "$ ./iambouali.sh"
logoCursorColor    = "#00f701"
[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "/posts"
[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"
